FROM quay.io/openshiftio/rhel-base-python3:latest
LABEL maintainer "Devtools <devtools@redhat.com>"
LABEL author "Devtools <devtools@redhat.com>"

# --------------------------------------------------------------------------------------------------------------
# Note: Need to remove cron job support for now as we are hitting user-permission issues when run on openshift
# --------------------------------------------------------------------------------------------------------------
# On centos, 'cron' is not available out-of-the-box.
# Reference: http://stackoverflow.com/questions/21802223/how-to-install-crontab-on-centos
# RUN yum install -y cronie

# Add data_importer_crontab file in the cron directory and give exec rights
# ADD scripts/data_importer_crontab /etc/cron.d/data_importer_crontab
# RUN chmod 0644 /etc/cron.d/data_importer_crontab

# Create the log file to be able to run tail
# RUN touch /var/log/cron.log

# Note: cron daemon ( crond ) will be invoked from within entry point
# --------------------------------------------------------------------------------------------------------------
RUN pip3 install --upgrade pip
RUN pip3 install git+https://github.com/fabric8-analytics/fabric8-analytics-utils.git@95ebbf2

COPY ./ /tmp/f8a_data_model/
COPY ./src /src
RUN cd /tmp/f8a_data_model && pip3 install .

ADD scripts/entrypoint.sh /bin/entrypoint.sh
ADD populate_schema.py /populate_schema.py

ENTRYPOINT ["/bin/entrypoint.sh"]